#!/bin/sh

APP=spotify
mkdir tmp;
cd ./tmp;
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
mv ./appimagetool-x86_64.AppImage ./appimagetool
chmod a+x ./appimagetool
wget -r -A spotify-1:*-x86_64.pkg.tar.zst -nd https://aur.andontie.net/x86_64/;
tar xf ./*.tar.zst;
mkdir $APP.AppDir;
mv ./opt ./$APP.AppDir;
cp ./$APP.AppDir/opt/spotify/*.desktop ./$APP.AppDir;
cp ./$APP.AppDir/opt/spotify/icons/spotify-linux-512.png ./$APP.AppDir/spotify-client.png;
echo '#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/opt/spotify/:${HERE}/opt/spotify/Apps/:${HERE}/opt/spotify/icons/:${HERE}/opt/spotify/locales/:${HERE}/opt/spotify/swiftshader/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/opt/spotify/:${HERE}/opt/spotify/swiftshader/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/opt/spotify/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${HERE}/opt/spotify/swiftshader/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
EXEC="${HERE}/opt/spotify/spotify"
exec "${EXEC}"' >> ./$APP.AppDir/AppRun;
chmod a+x ./$APP.AppDir/AppRun;
ARCH=x86_64 ./appimagetool -n ./$APP.AppDir
cd ..
mv ./tmp/Spotify*AppImage ./